# This workflow will take a commit/PR and build a new keyboards.v2.json while checking for duplicate vidpids

name: ViaMia-Release

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: node build.js
    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: |
          keyboards.v2.json
          
    - name: Push keyboard database to website
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
      with:
        source_file: 'keyboards.v2.json'
        destination_repo: 'ViaMia/ViaMia.github.io'
        user_email: 'viamia@tkon.nl'
        user_name: 'viamia'
        commit_message: 'Keyboard database update'
